# For more details on the format and content:
# https://github.com/joshyorko/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.12.11                     # https://anaconda.org/conda-forge/python
  - uv=0.10.2                         # https://anaconda.org/conda-forge/uv
  - pip:
      - robocorp-truststore==0.9.1      # https://pypi.org/project/robocorp-truststore
      - rpaframework==31.1.1          # https://rpaframework.org/releasenotes.html
      - rpaframework-assistant==5.0.0   # https://pypi.org/project/rpaframework-assistant
      - robocorp==3.0.0                 # https://pypi.org/project/robocorp
      - robocorp-browser==2.3.5         # https://pypi.org/project/robocorp-browser
      - openai==2.21.0                # https://pypi.org/project/openai/
      - python-dotenv==1.2.1            # https://pypi.org/project/python-dotenv/