# For more details on the format and content:
# https://github.com/joshyorko/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

#channels:
#  - conda-forge

dependencies:
  - python=3.12.11 # https://anaconda.org/conda-forge/python
  - uv=0.11.8
  - pip:
      - robocorp==3.1.1 # https://pypi.org/project/robocorp
      - robocorp-truststore==0.9.1 # https://pypi.org/project/robocorp-truststore
      - actions-work-items[all]==0.2.4 # https://pypi.org/project/actions-work-items
      - requests==2.32.5 # https://pypi.org/project/requests
      - gitpython==3.1.46 # https://pypi.org/project/GitPython
      - pandas==3.0.2 # https://pypi.org/project/pandas
